from __future__ import annotations

import json
from pathlib import Path

from django.core.management.base import BaseCommand

from pipeline.models import Artifact, PipelineRun
from pipeline.services import execute_pipeline_run
from pipeline.strategy_definitions import upsert_strategy_definition


MAG7_SYMBOLS = ["AAPL", "AMZN", "GOOGL", "META", "MSFT", "NVDA", "TSLA"]


class Command(BaseCommand):
    help = "Run the canonical MAG7 multi-model strategy backtest using the pipeline framework."

    def add_arguments(self, parser):
        parser.add_argument("--train-end-date", default="2019-12-31")
        parser.add_argument("--backtest-start-date", default="2020-01-01")
        parser.add_argument("--backtest-end-date", default="")
        parser.add_argument("--gate-quantile", type=float, default=0.5)
        parser.add_argument("--top-k", type=int, default=20)
        parser.add_argument("--rebalance-freq", default="W")
        parser.add_argument("--gross-exposure", type=float, default=0.8)
        parser.add_argument("--transaction-cost-bps", type=float, default=10.0)

    def handle(self, *args, **options):
        train_end_date = str(options["train_end_date"]).strip()
        backtest_start_date = str(options["backtest_start_date"]).strip()
        backtest_end_date = str(options["backtest_end_date"]).strip()
        gate_quantile = float(options["gate_quantile"])
        top_k = int(options["top_k"])
        rebalance_freq = str(options["rebalance_freq"]).strip().upper()
        gross_exposure = float(options["gross_exposure"])
        transaction_cost_bps = float(options["transaction_cost_bps"])
        strategy_definition = upsert_strategy_definition(
            slug="mag7-backtest-cli",
            name="MAG7 CLI Backtest Strategy",
            strategy_type="notebook_topk_v1",
            description="Notebook-style weekly top-k strategy generated by the MAG7 backtest command.",
            config={
                "gate_quantile": gate_quantile,
                "top_k": top_k,
                "rebalance_freq": rebalance_freq,
                "gross_exposure": gross_exposure,
                "prob_buy_field": "prob_buy",
                "ranking_field": "ranking",
                "ae_familiarity_field": "ae_familiarity",
                "combined_score_expr": "prob_buy * ranking * ae_familiarity",
                "selection_side": "long_only",
            },
        )

        def _run(name: str, requested_job: str, *, config: dict | None = None, input_ids: list[int] | None = None) -> Artifact:
            run = PipelineRun.objects.create(
                name=name,
                requested_job=requested_job,
                mode=PipelineRun.Mode.STRICT,
                status=PipelineRun.Status.PENDING,
                config=dict(config or {}),
            )
            return execute_pipeline_run(
                pipeline_run=run,
                target_job=requested_job,
                mode="strict",
                config=dict(config or {}),
                input_artifact_ids=list(input_ids or []),
            )

        universe_artifact = _run(
            "mag7-universe-live",
            "universe",
            config={"symbols": MAG7_SYMBOLS},
        )
        label_artifact = _run(
            "mag7-labels-live",
            "labels",
            config={"k_params": {"YE": [1, 2, 4, 8]}, "min_profit_pct": 0.0},
            input_ids=[int(universe_artifact.id)],
        )
        feature_artifact = _run(
            "mag7-features-live",
            "features",
            input_ids=[int(universe_artifact.id)],
        )

        classifier_model = _run(
            "mag7-fit-classifier-live",
            "fit_classifier",
            config={
                "target_col": "label",
                "split_ratio": 1.0,
                "model_name": "mag7_classifier_pre2020",
                "train_end_date": train_end_date,
            },
            input_ids=[int(feature_artifact.id), int(label_artifact.id)],
        )
        regressor_model = _run(
            "mag7-fit-regressor-live",
            "fit_regressor",
            config={
                "target_col": "trade_return",
                "split_ratio": 1.0,
                "model_name": "mag7_regressor_pre2020",
                "train_end_date": train_end_date,
            },
            input_ids=[int(feature_artifact.id), int(label_artifact.id)],
        )
        autoencoder_model = _run(
            "mag7-fit-autoencoder-live",
            "fit_autoencoder",
            config={
                "split_ratio": 1.0,
                "model_name": "mag7_autoencoder_pre2020",
                "train_end_date": train_end_date,
            },
            input_ids=[int(feature_artifact.id), int(label_artifact.id)],
        )

        score_window = {
            "score_start_date": backtest_start_date,
            "score_end_date": backtest_end_date,
            "label_artifact_id": int(label_artifact.id),
        }
        classifier_predictions = _run(
            "mag7-score-classifier-live",
            "score_classifier",
            config=score_window,
            input_ids=[int(classifier_model.id), int(feature_artifact.id)],
        )
        regressor_predictions = _run(
            "mag7-score-regressor-live",
            "score_regressor",
            config=score_window,
            input_ids=[int(regressor_model.id), int(feature_artifact.id)],
        )
        autoencoder_scores = _run(
            "mag7-score-autoencoder-live",
            "score_autoencoder",
            config=score_window,
            input_ids=[int(autoencoder_model.id), int(feature_artifact.id)],
        )

        strategy_artifact = _run(
            "mag7-strategy-live",
            "build_strategy_dataset",
            config={
                "strategy_definition_id": int(strategy_definition.id),
                "label_artifact_id": int(label_artifact.id),
                "prediction_artifact_ids": [
                    int(classifier_predictions.id),
                    int(regressor_predictions.id),
                    int(autoencoder_scores.id),
                ],
                "strategy_start_date": backtest_start_date,
                "strategy_end_date": backtest_end_date,
            },
            input_ids=[int(feature_artifact.id)],
        )

        backtest_artifact = _run(
            "mag7-backtest-live",
            "backtest_strategy",
            config={
                "backtest_start_date": backtest_start_date,
                "backtest_end_date": backtest_end_date,
                "transaction_cost_bps": transaction_cost_bps,
            },
            input_ids=[int(strategy_artifact.id)],
        )

        backtest_payload = dict(backtest_artifact.content or {})
        strategy_payload = dict(strategy_artifact.content or {})
        metadata = dict(backtest_artifact.metadata or {})
        equity_curve = list(metadata.get("equity_curve") or [])
        output = {
            "artifacts": {
                "universe": int(universe_artifact.id),
                "labels": int(label_artifact.id),
                "features": int(feature_artifact.id),
                "classifier_model": int(classifier_model.id),
                "regressor_model": int(regressor_model.id),
                "autoencoder_model": int(autoencoder_model.id),
                "classifier_predictions": int(classifier_predictions.id),
                "regressor_predictions": int(regressor_predictions.id),
                "autoencoder_scores": int(autoencoder_scores.id),
                "strategy_dataset": int(strategy_artifact.id),
                "backtest_result": int(backtest_artifact.id),
            },
            "strategy": strategy_payload,
            "strategy_definition": {
                "id": int(strategy_definition.id),
                "name": str(strategy_definition.name),
                "slug": str(strategy_definition.slug),
                "strategy_type": str(strategy_definition.strategy_type),
                "config": dict(strategy_definition.config),
            },
            "backtest": backtest_payload,
            "equity_curve_tail": equity_curve[-5:],
            "research_url": (
                f"/pipeline/research/symbol/AAPL/?label_artifact_id={int(label_artifact.id)}"
                f"&feature_artifact_id={int(feature_artifact.id)}"
                f"&prediction_artifact_id={int(classifier_predictions.id)}"
                f"&prediction_artifact_id={int(regressor_predictions.id)}"
                f"&prediction_artifact_id={int(autoencoder_scores.id)}"
                f"&strategy_artifact_id={int(strategy_artifact.id)}"
                f"&backtest_artifact_id={int(backtest_artifact.id)}"
            ),
            "strategy_url": f"/pipeline/strategies/{int(strategy_artifact.id)}/",
            "backtest_url": f"/pipeline/backtests/{int(backtest_artifact.id)}/",
        }

        summary_path = Path("data") / "pipeline_artifacts" / "mag7_backtest_summary.json"
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.write_text(json.dumps(output, indent=2, sort_keys=True), encoding="utf-8")

        self.stdout.write(self.style.SUCCESS(json.dumps(output, indent=2, sort_keys=True)))
        self.stdout.write(self.style.SUCCESS(f"Summary written to {summary_path}"))
