from django.urls import path

from .views import (
    artifact_detail,
    latest_artifact_by_type,
    artifact_list_by_type,
    artifact_symbol_breakdown,
    backtest_detail,
    pipeline_lab,
    pipeline_strategies,
    pipeline_job_catalog,
    pipeline_status_board,
    pipeline_run_latest,
    pipeline_run_delete,
    pipeline_run_rename,
    pipeline_cohorts,
    pipeline_run_list,
    pipeline_run_start,
    pipeline_run_status,
    pipeline_research_reports,
    pipeline_diagnostic_reports,
    pipeline_oracle_reports,
    pipeline_feature_attribution_reports,
    pipeline_market_state_api,
    pipeline_market_situations,
    pipeline_opportunities,
    pipeline_top_opportunities,
    pipeline_portfolio_analysis,
    pipeline_rl_policy_reports,
    pipeline_stock_intelligence,
    symbol_research_view,
    strategy_detail,
    strategy_definition_edit,
    strategy_definition_list,
    pipeline_ui,
    artifact_preview,
)

urlpatterns = [
    path("ui/", pipeline_ui, name="pipeline-ui"),
    path("lab/", pipeline_lab, name="pipeline-lab"),
    path("strategies/", pipeline_strategies, name="pipeline-strategies"),
    path("cohorts/", pipeline_cohorts, name="pipeline-cohorts"),
    path("reports/", pipeline_research_reports, name="pipeline-research-reports"),
    path("diagnostics/", pipeline_diagnostic_reports, name="pipeline-diagnostic-reports"),
    path("oracle-reports/", pipeline_oracle_reports, name="pipeline-oracle-reports"),
    path("feature-attribution/", pipeline_feature_attribution_reports, name="pipeline-feature-attribution-reports"),
    path("rl-policies/", pipeline_rl_policy_reports, name="pipeline-rl-policy-reports"),
    path("insights/market-state/", pipeline_market_state_api, name="pipeline-market-state-api"),
    path("market-situations/", pipeline_market_situations, name="pipeline-market-situations"),
    path("opportunities/", pipeline_opportunities, name="pipeline-opportunities"),
    path("top-opportunities/", pipeline_top_opportunities, name="pipeline-top-opportunities"),
    path("stock-intelligence/", pipeline_stock_intelligence, name="pipeline-stock-intelligence"),
    path("stock/<str:symbol>/", pipeline_stock_intelligence, name="pipeline-stock-intelligence-symbol"),
    path("portfolio-analysis/", pipeline_portfolio_analysis, name="pipeline-portfolio-analysis"),
    path("strategy-definitions/", strategy_definition_list, name="pipeline-strategy-definitions"),
    path("strategy-definitions/<int:definition_id>/", strategy_definition_edit, name="pipeline-strategy-definition-edit"),
    path("strategies/<int:artifact_id>/", strategy_detail, name="pipeline-strategy-detail"),
    path("backtests/<int:artifact_id>/", backtest_detail, name="pipeline-backtest-detail"),
    path("research/symbol/<str:symbol>/", symbol_research_view, name="pipeline-symbol-research"),
    path("runs/start/", pipeline_run_start, name="pipeline-run-start"),
    path("runs/list/", pipeline_run_list, name="pipeline-run-list"),
    path("runs/latest/", pipeline_run_latest, name="pipeline-run-latest"),
    path("runs/<int:pipeline_run_id>/", pipeline_run_status, name="pipeline-run-status"),
    path("runs/<int:pipeline_run_id>/delete/", pipeline_run_delete, name="pipeline-run-delete"),
    path("runs/<int:pipeline_run_id>/rename/", pipeline_run_rename, name="pipeline-run-rename"),
    path("artifacts/<int:artifact_id>/", artifact_detail, name="pipeline-artifact-detail"),
    path("artifacts/<int:artifact_id>/preview/", artifact_preview, name="pipeline-artifact-preview"),
    path("artifacts/<int:artifact_id>/symbol-breakdown/", artifact_symbol_breakdown, name="pipeline-artifact-symbol-breakdown"),
    path("artifacts/latest/", latest_artifact_by_type, name="pipeline-artifact-latest"),
    path("artifacts/list/", artifact_list_by_type, name="pipeline-artifact-list"),
    path("catalog/", pipeline_job_catalog, name="pipeline-job-catalog"),
    path("status-board/", pipeline_status_board, name="pipeline-status-board"),
]
