# Generated by Django 6.0.2 on 2026-02-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmp', '0005_remove_technical_rsi_section_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='symbolsectionhistorical',
            name='fmp_symbolsectionhistorical_symbol_section_record_key_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='symbolsectionsnapshot',
            name='fmp_symbolsectionsnapshot_symbol_section_key_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='symbolsectionstate',
            name='fmp_symbolsectionstate_symbol_section_key_uniq',
        ),
        migrations.RenameIndex(
            model_name='symbolsectionhistorical',
            new_name='fmp_symbols_symbol__02ed38_idx',
            old_name='fmp_hist_sym_sect_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='symbolsectionhistorical',
            unique_together={('symbol', 'section_key', 'record_key')},
        ),
        migrations.AlterUniqueTogether(
            name='symbolsectionsnapshot',
            unique_together={('symbol', 'section_key')},
        ),
        migrations.AlterUniqueTogether(
            name='symbolsectionstate',
            unique_together={('symbol', 'section_key')},
        ),
    ]
