# Generated by Django 6.0.2 on 2026-02-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmp', '0007_macro_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='macroobservation',
            new_name='fmp_macroob_series__673b11_idx',
            old_name='fmp_macroob_series__7b6ff4_idx',
        ),
    ]
