# Generated by Django 6.0.2 on 2026-02-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmp', '0010_split_macro_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='economicindicatorobservation',
            new_name='fmp_economi_series__e9e60b_idx',
            old_name='fmp_econo_series__9a85ae_idx',
        ),
        migrations.RenameIndex(
            model_name='treasuryrateobservation',
            new_name='fmp_treasur_series__d6e9b4_idx',
            old_name='fmp_treas_series__648ad3_idx',
        ),
        migrations.AlterField(
            model_name='treasuryrateobservation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='fmp.treasuryrateseries'),
        ),
    ]
