# Generated by Django 6.0.2 on 2026-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmp', '0012_universedownloadjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='universedownloadjob',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
